--- #YAML:1.0
name:               Scope-Upper
version:            0.12
abstract:           Act on upper scopes.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    Config:               0
    ExtUtils::MakeMaker:  0
build_requires:
    base:                 0
    Exporter:             0
    ExtUtils::MakeMaker:  0
    Test::More:           0
    XSLoader:             0
requires:
    base:      0
    Exporter:  0
    perl:      5.006
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Scope-Upper
    homepage:    http://search.cpan.org/dist/Scope-Upper/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2FScope-Upper.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     1
