--- #YAML:1.0
name:               Scope-Upper
version:            0.08
abstract:           Act on upper scopes.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Exporter:  0
    perl:      5.006
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Scope-Upper
    homepage:    http://search.cpan.org/dist/Scope-Upper/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl/modules/Scope-Upper.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
